#version: '3.1'
#services:
#  db:
#    hostname: mysql
#    image: mysql:5.7
#    restart: always
#    volumes:
#      - db_data:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#    ports:
#      - 3306:3306
#
#volumes:
#  db_data:

version: '3.7'
services:
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=elcproduct
      - POSTGRES_PASSWORD=elcproduct!@#
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: